### PR TITLE
Hotfix/markdown support paraphernalia

### PR DESCRIPTION
**Pull request by Abekonge**
Some smaller fixes relating to markdown in lichen:

* [don't show navigation back on index.md](https://github.com/soapdog/lichen-with-markdown/commit/69ff0d282debf4fb86e2311c348bf33b94f7f174)
* [markdown cheatsheet](https://github.com/soapdog/lichen-with-markdown/commit/0daa5b7d757ab7c3787f8ec3cf2339d4d78493d5)
* [show markdown help when markdown file.](https://github.com/soapdog/lichen-with-markdown/commit/8afc8996fe9504089cd14e04b0b1d80ae3d816de)
* [enable markdown extra syntax](https://github.com/soapdog/lichen-with-markdown/commit/3c9ae1f49b9926bc628f5ecdb87be39490ced95d)
* [disable gemini style links](https://github.com/soapdog/lichen-with-markdown/commit/3a4e2fd6565b7c4be3657a8aa4401e444e6036f7)

### CODE REVIEW

**Comment by Abekonge** [comment]
@soapdog @mhfowler Hey hope this makes sense here! Talked with @mhfowler about it - let me know if anything needs to be changed.

**Comment by mhfowler** [comment]
awesome. cool to have the markdown cheat sheet with nice dandi image :-)

**Comment by mhfowler** [comment]
@soapdog - @Abekonge and I were discussing continuing some work on this, in particular because the latest lichen has switched to using forth (https://lichen.sensorstation.co/), which is cool, but we were considering developing the php version a bit further as we think its  actually nice that its in php which is a language a lot of people are already comfortable with . and further changing it to be lichen-markdown instead of gemini, as we prefer markdown 

which is all to say, if you are up for adding us as collaborators to this repo could be nice, or if you prefer we can start a different repo for this lil project

**Comment by soapdog** [comment]
Thanks a ton for the enhancements folks. 

I have not been touching this repo much but I really like this source code. I'm thinking about adding both of you as collaborators here so that you don't depend on me to move it forward, would you both be OK with that?

@Abekonge @mhfowler

**Comment by Abekonge** [comment]
> Thanks a ton for the enhancements folks.
> 
> I have not been touching this repo much but I really like this source code. I'm thinking about adding both of you as collaborators here so that you don't depend on me to move it forward, would you both be OK with that?
> 
> @Abekonge @mhfowler

@soapdog Yes that would be cool! This small project is really nice, and people in my community use it - so it is nice that we can just work from the same repo.

We were talking about moving to [codeberg](https://codeberg.org/), as an ideological "adjecent possible" action - and possibly rename the project, since the original lLichen is now in forth, this one could be understood as `lichen-php` as well as `lichen-markdown` - so I was thinking about given it a new less "tech"-descriptive name, such as `lichen-punk` or `lichen-solpunk`, (@mhfowler and my collab on this grew out of the solpunk-gathering in Denmark).

So, should we "archive" the project here - pointing to a new repo at codeberg, or just stay here? I'm okay with staying, I just find fun in this kind of project nest building :)

**Comment by soapdog** [comment]
@Abekonge by all means, you folks don't need to stay using this repo. If you're more comfortable with codeberg, move the code there and send me the URL. I can update the README with a link to the new place and archive the repo.

**Comment by Abekonge** [comment]
@soapdog  

cool! I've made the new repo at codeberg here: https://codeberg.org/ukrudt.net/lichen-markdown (there is a weird date on your latest merge commit of my branch, I was trying to change my commit email/username of my old  commits (my work email was on them), and messed up your merge commit metadata - I fixed it, but the commit date was set to yesterday in the process, sorry about that.)

If you want to I will invite you to the repo as an owner, but you need to make a codeberg user first. If you prefer not to, that is perfectly alright as well!

**Pull request merged**
